config/routes.rb
Rails.application.routes.draw do
devise_for :users
  namespace :api do
    namespace :v1 do
      resources :trains do
        resources :workouts
      end
    end
  end

      # get '/users/sign_out' => 'devise/sessions#destroy'


  resources :trains do 
    post 'done', action: :done
    get 'current_workout', action: :current_workout
    
  end
  
  resources :workouts
  resources :exercises
  resources :train_blocks
  resources :train_plans
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  # devise_for :users do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :train
  belongs_to :exercise
end

app/controllers/api/v1/workouts_controller.rb
class Api::V1::WorkoutsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @workouts = Workout.all
    if @workouts
      render json: @workouts, status: 200
    else
      render json: "Workouts Not Found", status: 404
    end
  end

  # def show
  #   @workout = Workout.find(params[:id])
  #   if @workout
  #     render json: @workout, status: 200
  #   else
  #     render json: "Workout Not Found", status: 404
  #   end
  # end

  def create
    @workout = Workout.new(workout_params)
    if @workout.save
      render json: @workout, status: 201
    else
      render json: "Workout Not Found", status: 400
    end
  end

  # def destroy
  #   @workout = Workout.find(params[:id])
  #   if @workout
  #     @workout.destroy
  #     render json: "Workout deleted", status: 204
  #   end
  # end

  private
  def workout_params
    params.require(:workout).permit(:train_id, :exercise_id)
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[ show edit update destroy ]

  # GET /workouts or /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1 or /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts or /workouts.json
  def create
    @workout = Workout.new(workout_params)
    @workout.save
    # respond_to do |format|
    #   if @workout.save
    #     format.html { redirect_to workout_url(@workout), notice: "Workout was successfully created." }
    #     format.json { render :show, status: :created, location: @workout }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @workout.errors, status: :unprocessable_entity }
    #   end
    # end
    # redirect_to train_current_workout_url(train_id: @workout.train_id)
    # redirect_to controller: 'trains', action: :current_workout, train_id: @workout.train_id
  end

  # PATCH/PUT /workouts/1 or /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to workout_url(@workout), notice: "Workout was successfully updated." }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1 or /workouts/1.json
  def destroy
    @workout.destroy!

    respond_to do |format|
      format.html { redirect_to workouts_url, notice: "Workout was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workout_params
      params.require(:workout).permit(:train_id, :exercise_id)
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_with(model: workout) do |f| %>
  <% if workout.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
        <% workout.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= f.label :train_id, style: "display: block" %>
    <%= f.text_field :train_id %>
  </div>

<br>

<div>
  <%= f.label :exercise_id, style: "display: block" %>
  <%= f.collection_select :exercise_id, Exercise.all, :id, :name_with_initial, prompt: true %>
</div>

<br>

  <button type="submit" class="btn btn-primary">Create Workout </button>

<% end %>

app/views/workouts/_workout.html.erb
<div id="<%= dom_id workout %>">
  <p>
    <strong>Train:</strong>
    <%= workout.train_id %>
  </p>


  <p>
    <strong>Exercise:</strong>
    <%= workout.exercise_id %>
  </p>

</div>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Show this workout", @workout %> |
  <%= link_to "Back to workouts", workouts_path %>
</div>

app/views/workouts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Workouts</h1>

<div id="workouts">
  <% @workouts.each do |workout| %>
    <%= render workout %>
    <p>
      <%= link_to "Show this workout", workout %>
    </p>
  <% end %>
</div>

<%= link_to "New workout", new_workout_path %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Back to workouts", workouts_path %>
</div>

app/views/workouts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @workout %>

<div>
  <%= link_to "Edit this workout", edit_workout_path(@workout) %> |
  <%= link_to "Back to workouts", workouts_path %>

  <%= button_to "Destroy this workout", @workout, method: :delete %>
</div>