config/routes.rb
Rails.application.routes.draw do
devise_for :users
  namespace :api do
    namespace :v1 do
      resources :trains do
        resources :workouts
      end
    end
  end

      # get '/users/sign_out' => 'devise/sessions#destroy'


  resources :trains do 
    post 'done', action: :done
    get 'current_workout', action: :current_workout
    
  end
  
  resources :workouts
  resources :exercises
  resources :train_blocks
  resources :train_plans
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  # devise_for :users do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :train_plan
  delegate :exercises, to: :train_plan
  has_many :workouts

  def steps
    steps = []
    TrainPlan.find(train_plan_id).exercises.each do |set|
      steps << set
    end
    steps
  end

  def done?
    current_exercise.id == steps.last.id
  end

  def current_exercise
    steps[current_step_number]
  end

  def show_exercise
    trblock = TrainBlock.find(current_exercise.train_block_id)
    exercise = trblock.title
    exercise
  end

  def done!
    update!(current_step_number: current_step_number + 1)
  end

  def finish_exercise
    # redirect_to controller: 'workouts', action: :create, params: { workout: { train_id: 1, exercise_id: 1 } } 
    Workout.create!(train_id: id, exercise_id: current_exercise.id)
  end

end

app/controllers/api/v1/trains_controller.rb
class Api::V1::TrainsController < ApplicationController
  skip_before_action :verify_authenticity_token

def index
    @trains = Train.all
      if @trains
        render json: @trains, status: 200
      else
        render json: "Trains Not Found", status: 404
      end
  end

  # def show
  #     @train = Train.find(params[:id])
  #     if @train
  #       render json: @train, status: 200
  #     else
  #       render json: "Train Not Found", status: 404
  #     end
  # end

  def create
    @train = Train.new(train_params)
    if @train.save
      render json: @train, status: 201
    else
      render json: 
      { :errors => @train.errors.as_json }, status: 400
    end
  end

  # def destroy
  #   @train = Train.find(params[:id])
  #   if @train
  #     @train.destroy
  #     render json: "Train deleted"
  #   end
  # end

  private
    def train_params
      params.require(:train).permit(:train_plan_id)
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /trains or /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1 or /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains or /trains.json
  def create
    @train = Train.new(train_params)
    @train.save
    redirect_to train_current_workout_url(train_id: @train.id)
  end

  def current_workout
    train = Train.find(params[:train_id])
    @exercise = train.current_exercise
    @exercise_name = train.show_exercise
    @train_id = train.id
  end

  def done
    train = Train.find(params[:train_id])

    if train.done?
      redirect_to action: :new
    else
      train.finish_exercise
      train.done!
      redirect_to action: :current_workout
    end
  end

  # PATCH/PUT /trains/1 or /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to train_url(@train), notice: "Train was successfully updated." }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1 or /trains/1.json
  def destroy
    @train.destroy!

    respond_to do |format|
      format.html { redirect_to trains_url, notice: "Train was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def train_params
      params.require(:train).permit(:train_plan_id)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_with(model: train) do |form| %>
  <% if train.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
        <% train.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <h5>
      Выберете TrainPlan:
    </h5>
  </div>

  <div>
    <%= form.label :train_plan_id, style: "display: block" %>
    <%= form.collection_select :train_plan_id, TrainPlan.all, :id, :name_with_initial, prompt: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<div id="<%= dom_id train %>">
  <p>
    <strong>Train plan:</strong>
    <%= train.train_plan_id %>
  </p>

</div>

app/views/trains/current_workout.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <p>
    <strong>Exercise:</strong>
    <%= @exercise_name %>
  </p>
  <p>
    <strong>Train_block_id:</strong>
    <%= @exercise.train_block_id %>
  </p>
  <p>
    <strong>Approach_number:</strong>
    <%= @exercise.approach_number %>
  </p>
  <p>
    <strong>Repeats:</strong>
    <%= @exercise.repeats %>
  </p>
  <p>
    <strong>Mass:</strong>
    <%= @exercise.mass %>
  </p>
  <p>
    <strong>Train.id:</strong>
    <%= @train_id %>
  </p>


 <%= button_to 'Save exercise', method: :post, action: :done %> 

  <%# <%= button_to 'Save exercise', method: :post, controller: 'workouts', action: :create, params: { workout: { train_id: @train_id, exercise_id: @exercise.id } } %> 

</div>

app/views/trains/edit.html.erb
<h1>Editing train</h1>

<%= render "form", train: @train %>

<br>

<div>
  <%= link_to "Show this train", @train %> |
  <%= link_to "Back to trains", trains_path %>
</div>

app/views/trains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Trains</h1>

<%= link_to "New train", new_train_path %>

<div id="trains">
  <% @trains.each do |train| %>
    <%= render train %>
    <p>
      <%= link_to "Show this train", train %>
    </p>
  <% end %>
</div>

<%= link_to "New train", new_train_path %>

app/views/trains/new.html.erb
<h1>New train</h1>

<%= render "form", train: @train %>

<br>

<div>
  <%= link_to "Back to trains", trains_path %>
</div>

app/views/trains/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @train %>

<div>
  <%= link_to "Edit this train", edit_train_path(@train) %> |
  <%= link_to "Back to trains", trains_path %>

  <%= button_to "Destroy this train", @train, method: :delete %>
</div>