config/routes.rb
Rails.application.routes.draw do
devise_for :users
  namespace :api do
    namespace :v1 do
      resources :trains do
        resources :workouts
      end
    end
  end

      # get '/users/sign_out' => 'devise/sessions#destroy'


  resources :trains do 
    post 'done', action: :done
    get 'current_workout', action: :current_workout
    
  end
  
  resources :workouts
  resources :exercises
  resources :train_blocks
  resources :train_plans
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  # devise_for :users do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  
end

app/models/train_plan.rb
class TrainPlan < ApplicationRecord
  has_many :trains
  has_many :train_blocks
  has_many :exercises, through: :train_blocks

  validates :title, presence: true, length: { minimum: 3 }

  def name_with_initial
    "Название: #{title}"
  end
end

app/controllers/train_plans_controller.rb
class TrainPlansController < ApplicationController
  before_action :set_train_plan, only: %i[ show edit update destroy ]

  # GET /train_plans or /train_plans.json
  def index
    @train_plans = TrainPlan.all

  end

  # GET /train_plans/1 or /train_plans/1.json
  def show
  end

  # GET /train_plans/new
  def new
    @train_plan = TrainPlan.new
  end

  # GET /train_plans/1/edit
  def edit
  end

  # POST /train_plans or /train_plans.json
  def create
    @train_plan = TrainPlan.new(train_plan_params)

    respond_to do |format|
      if @train_plan.save
        format.html { redirect_to train_plan_url(@train_plan), notice: "Train plan was successfully created." }
        format.json { render :show, status: :created, location: @train_plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @train_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /train_plans/1 or /train_plans/1.json
  def update
    respond_to do |format|
      if @train_plan.update(train_plan_params)
        format.html { redirect_to train_plan_url(@train_plan), notice: "Train plan was successfully updated." }
        format.json { render :show, status: :ok, location: @train_plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @train_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /train_plans/1 or /train_plans/1.json
  def destroy
    @train_plan.destroy!

    respond_to do |format|
      format.html { redirect_to train_plans_url, notice: "Train plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train_plan
      @train_plan = TrainPlan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def train_plan_params
      params.require(:train_plan).permit(:title)
    end
end

app/helpers/train_plans_helper.rb
module TrainPlansHelper
end

app/views/train_plans/_form.html.erb
<%= form_with(model: train_plan) do |form| %>
  <% if train_plan.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(train_plan.errors.count, "error") %> prohibited this train_plan from being saved:</h2>

      <ul>
        <% train_plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_area :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/train_plans/_train_plan.html.erb
<div id="<%= dom_id train_plan %>">
  <p>
    <strong>Title:</strong>
    <%= train_plan.title %>
  </p>

</div>

app/views/train_plans/edit.html.erb
<h1>Editing train plan</h1>

<%= render "form", train_plan: @train_plan %>

<br>

<div>
  <%= link_to "Show this train plan", @train_plan %> |
  <%= link_to "Back to train plans", train_plans_path %>
</div>

app/views/train_plans/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Train plans</h1>

<div id="train_plans">
  <% @train_plans.each do |train_plan| %>
    <%= render train_plan %>
    <p>
      <%= link_to "Show this train plan", train_plan %>
    </p>
  <% end %>
</div>

<%= link_to "New train plan", new_train_plan_path %>

app/views/train_plans/new.html.erb
<h1>New train plan</h1>

<%= render "form", train_plan: @train_plan %>

<br>

<div>
  <%= link_to "Back to train plans", train_plans_path %>
</div>

app/views/train_plans/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @train_plan %>

<div>
  <%= link_to "Edit this train plan", edit_train_plan_path(@train_plan) %> |
  <%= link_to "Back to train plans", train_plans_path %>

  <%= button_to "Destroy this train plan", @train_plan, method: :delete %>
</div>