config/routes.rb
Rails.application.routes.draw do
devise_for :users
  namespace :api do
    namespace :v1 do
      resources :trains do
        resources :workouts
      end
    end
  end

      # get '/users/sign_out' => 'devise/sessions#destroy'


  resources :trains do 
    post 'done', action: :done
    get 'current_workout', action: :current_workout
    
  end
  
  resources :workouts
  resources :exercises
  resources :train_blocks
  resources :train_plans
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  # devise_for :users do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  
end

app/models/train_block.rb
class TrainBlock < ApplicationRecord
  belongs_to :train_plan
  has_many :exercises
  validates :title, presence: true, length: { minimum: 3 }
  validates :sequence_number, comparison: { greater_than: 0 }
end

app/controllers/train_blocks_controller.rb
class TrainBlocksController < ApplicationController
  before_action :set_train_block, only: %i[ show edit update destroy ]

  # GET /train_blocks or /train_blocks.json
  def index
    @train_blocks = TrainBlock.includes(:train_plan)
  end

  # GET /train_blocks/1 or /train_blocks/1.json
  def show
  end

  # GET /train_blocks/new
  def new
    @train_block = TrainBlock.new
  end

  # GET /train_blocks/1/edit
  def edit
  end

  # POST /train_blocks or /train_blocks.json
  def create
    @train_block = TrainBlock.new(train_block_params)

    respond_to do |format|
      if @train_block.save
        format.html { redirect_to train_block_url(@train_block), notice: "Train block was successfully created." }
        format.json { render :show, status: :created, location: @train_block }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @train_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /train_blocks/1 or /train_blocks/1.json
  def update
    respond_to do |format|
      if @train_block.update(train_block_params)
        format.html { redirect_to train_block_url(@train_block), notice: "Train block was successfully updated." }
        format.json { render :show, status: :ok, location: @train_block }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @train_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /train_blocks/1 or /train_blocks/1.json
  def destroy
    @train_block.destroy!

    respond_to do |format|
      format.html { redirect_to train_blocks_url, notice: "Train block was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train_block
      @train_block = TrainBlock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def train_block_params
      params.require(:train_block).permit(:train_plan_id, :title, :sequence_number)
    end
end

app/helpers/train_blocks_helper.rb
module TrainBlocksHelper
end

app/views/train_blocks/_form.html.erb
<%= form_with(model: train_block) do |form| %>
  <% if train_block.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(train_block.errors.count, "error") %> prohibited this train_block from being saved:</h2>

      <ul>
        <% train_block.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :train_plan_id, style: "display: block" %>
    <%= form.text_field :train_plan_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_area :title %>
  </div>

  <div>
    <%= form.label :sequence_number, style: "display: block" %>
    <%= form.number_field :sequence_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/train_blocks/_train_block.html.erb
<div id="<%= dom_id train_block %>">
  <p>
    <strong>Train plan title:</strong>
    <%= train_block.train_plan.title %>
  </p>

  <p>
    <strong>Train block title:</strong>
    <%= train_block.title %>
  </p>

  <p>
    <strong>Sequence number:</strong>
    <%= train_block.sequence_number %>
  </p>

</div>

app/views/train_blocks/edit.html.erb
<h1>Editing train block</h1>

<%= render "form", train_block: @train_block %>

<br>

<div>
  <%= link_to "Show this train block", @train_block %> |
  <%= link_to "Back to train blocks", train_blocks_path %>
</div>

app/views/train_blocks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Train blocks</h1>

<div id="train_blocks">
  <% @train_blocks.each do |train_block| %>
    <%= render train_block %>
    <p>
      <%= link_to "Show this train block", train_block %>
    </p>
  <% end %>
</div>

<%= link_to "New train block", new_train_block_path %>

app/views/train_blocks/new.html.erb
<h1>New train block</h1>

<%= render "form", train_block: @train_block %>

<br>

<div>
  <%= link_to "Back to train blocks", train_blocks_path %>
</div>

app/views/train_blocks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @train_block %>

<div>
  <%= link_to "Edit this train block", edit_train_block_path(@train_block) %> |
  <%= link_to "Back to train blocks", train_blocks_path %>

  <%= button_to "Destroy this train block", @train_block, method: :delete %>
</div>